// lessons.js
export const lessonsData = {
  "Lesson 1: Basics": {
    text: [
      "Hangul consists of vowels and consonants.",
      "For example: ㅁ (m) and ㅏ (a) combine to form 마 (ma).",
      "Hangul is phonetic, making it easy to learn pronunciation.",
      "Start with these basics:",
      "ㅏ (a) [a]",
      "ㅗ (o) [o]",
      "ㅡ (eu) [ɯ]",
      "ㅎ (h) [h]",
      "Examples:",
      "마 (ma) [ma]",
      "바 (ba) [pa]",
      "법 (beop) [pʌp] - Law."
    ],
    korean: [
      "",
      "",
      "",
      "",
      "ㅏ",
      "ㅗ",
      "ㅡ",
      "ㅎ",
      "",
      "마",
      "바",
      "법"
    ]
  },
  "Lesson 2: Greetings": {
    text: [
      "1. 안녕하세요 (Annyeonghaseyo): \n • Formal greeting used when meeting someone on the street or entering a shop. \n • Example: “Hello!” or “Good day!”",
      "2. 안녕 (Annyeong):\n• Informal greeting used among friends, peers, or younger people.\n• Example: “Hi!” or “Bye!”",
      "3. 여보세요 (Yeoboseyo):\n• Used when starting a phone call.\n• Example: “Hello?”",
      "4. 반갑습니다 (Bangapseumnida):\n• Used when meeting someone for the first time or after a long time.\n• Example: “Nice to meet you!”",
      "5. 수고하세요 (Sugohaseyo):\n• A polite phrase used to appreciate someone’s hard work.\n• Example: “Keep up the good work!”",
      "6. 잘 자요 (Jal jayo) / 안녕히 주무세요 (Annyeonghi jumuseyo):\n• Used to say “Good night.” “잘 자요” is informal, and “안녕히 주무세요” is formal.",
      "7. 좋은 하루 되세요 (Joeun haru doeseyo):\n • A polite phrase wishing someone a good day.\n • Example: “Have a nice day!”",
      "8. 안녕히 가세요 (Annyeonghi gaseyo) / 안녕히 계세요 (Annyeonghi gyeseyo): \n • 안녕히 가세요: “Goodbye” (to someone leaving). It literally means, “Go peacefully.” \n • 안녕히 계세요: “Goodbye” (to someone staying). It literally means, “Stay peacefully.”",
      "9. 오랜만이에요 (Oraenmanieyo): \n • “It’s been a while” or “Long time no see.”"
    ],
    korean: [
      "안녕하세요",
      "안녕",
      "여보세요",
      "반갑습니다",
      "수고하세요",
      "잘 자요, 안녕히 주무세요",
      "좋은 하루 되세요",
      "안녕히 가세요, 안녕히 계세요",
      "오랜만이에요"
    ]
  },
    "Lesson 3: Numbers": {
    text: [
      "1. Native Korean Numbers (고유어 숫자):\nUsage:\n• Used for counting things like age, people, and objects.\n• Typically used for numbers 1 through 99.",
      "  • 1: 하나 (Hana)",
      "  • 2: 둘 (Dul)",
      "  • 3: 셋 (Set)",
      "  • 4: 넷 (Net)",
      "  • 5: 다섯 (Daseot)",
      "  • 6: 여섯 (Yeoseot)",
      "  • 7: 일곱 (Ilgop)",
      "  • 8: 여덟 (Yeodeol)",
      "  • 9: 아홉 (Ahop)",
      "  • 10: 열 (Yeol)",
      "2. Sino-Korean Numbers (한자어 숫자):\nUsage:\n• Used for dates, time, phone numbers, prices, and large numbers.\n,• Commonly used for numbers 100 and above.",
      "  • 1: 일 (Il)",
      "  • 2: 이 (I)",
      "  • 3: 삼 (Sam)",
      "  • 4: 사 (Sa)",
      "  • 5: 오 (O)",
      "  • 6: 육 (Yuk)",
      "  • 7: 칠 (Chil)",
      "  • 8: 팔 (Pal)",
      "  • 9: 구 (Gu)",
      "  • 10: 십 (Sip)"
    ],
    korean: [
      "",
      "하나",
      "둘",
      "셋",
      "넷",
      "다섯",
      "여섯",
      "일곱",
      "여덟",
      "아홉",
      "열",
      "",
      "일",
      "이",
      "삼",
      "사",
      "오",
      "육",
      "칠",
      "팔",
      "구",
      "십"
    ]
  },
  "Lesson 4: Days and Time": {
    text: [
      "Days of the week:",
      "월요일 (Wolyoil) - Monday [wʌɭ.jo.il]",
      "화요일 (Hwayoil) - Tuesday [hwa.jo.il]",
      "수요일 (Suyoil) - Wednesday [su.jo.il]",
      "목요일 (Mogyoil) - Thursday [mo.gjo.il]",
      "Time basics:",
      "한시 (Hanshi) - 1 o’clock. [han.ɕi]",
      "밤 (Bam) - Night. [pam]",
      "오전 (Ojeon) - Morning. [o.dʑʌn]",
      "Examples:",
      "여름밤 (Yeoreum bam) - Summer night. [jʌ.ɾɯm bam]",
      "아침 시간 (Achim sigan) - Morning time. [a.tɕʰim ɕi.gan]"
    ],
    korean: [
      "",
      "월요일",
      "화요일",
      "수요일",
      "목요일",
      "",
      "한시",
      "밤",
      "오전",
      "",
      "여름밤",
      "아침 시간"
    ]
  },
    "Lesson 5: Food and Dining": {
    text: [
      "Essential phrases:",
      "1. 메뉴 좀 볼 수 있을까요? (Menu jom bol su isseulkkayo?) - Can I see the menu, please? [me.nju dʑom bol su i.sɯl.k͈a.jo]",
      "2. 뭐를 추천하시나요? (Mweoreul chucheonhashinayo?) - What do you recommend? [mwʌ.ɾɯl tɕʰu.tɕʰʌn.ha.ɕi.na.jo]",
      "3. 오늘의 추천 요리가 있나요? (Oneureui chucheon yoriga innayo?) - Do you have any specials today? [o.nɯ.ɾe.ɰi tɕʰu.tɕʰʌn jo.ɾi.ga in.na.jo]",
      "4. 김치찌개 주문할게요. (Kimchi jjigae jumunhalgeyo.) - I would like to order kimchi soup. [kim.tɕʰi tɕ͈i.gɛ dʑu.mun.hal.ge.jo]",
      "5. 음료수 좀 주시겠어요? (Eumryosu jom jushigesseoyo?) - Can I get a drink? [ɯm.ɾjo.su dʑom dʑu.ɕi.gɛ.s͈ʌ.jo]",
      "6. 불고기를 추가할 수 있을까요? (Bulgogireul chuga hal su isseulkkayo?) - Can we add bulgogi to our order? [pul.go.gi.ɾɯl tɕʰu.ga hal su i.sɯl.k͈a.jo]",
      "7. 계산서 좀 주세요. (Gyesanseo jom juseyo.) - Can I have the bill, please? [kje.san.sʌ dʑom dʑu.se.jo]"
    ],
    korean: [
      "",
      "메뉴 좀 볼 수 있을까요?",
      "뭐를 추천하시나요?",
      "오늘의 추천 요리가 있나요?",
      "김치찌개 주문할게요.",
      "음료수 좀 주시겠어요?",
      "불고기를 추가할 수 있을까요?",
      "계산서 좀 주세요."
    ]
  },
  "Lesson 6: Shopping": {
    text: [
      "Shopping essentials:",
      "1. 이거 얼마예요? (Igeo eolmayeyo?) - How much is this? [i.gʌ ʌl.ma.je.jo]",
      "2. 좀 깎아주세요 (Jom kakkajuseyo) - Please give me a discount. [tɕom kak.kʰa.dʑu.se.jo]",
      "3. 더 주세요 (Deo juseyo) - Please add more. [tʌ dʑu.se.jo]",
      "4. 가격 (Gagyeok) - Price. [ka.gjʌk]",
      "5. 세일 (Seil) - Sale. [se.il]",
      "Phrases to know:",
      "한 번 입어보세요 (Han beon ibeo boseyo) - Try it on. [han bʌn i.bʌ bo.se.jo]",
      "할인 (Harin) - Discount. [ha.ɾin]"
    ],
    korean: [
      "",
      "이거 얼마예요",
      "좀 깎아주세요",
      "더 주세요",
      "가격",
      "세일",
      "",
      "한 번 입어보세요",
      "할인"
    ]
  },
  "Lesson 7: Travel and Directions": {
    text: [
      "Phrases:",
      "1. 왼쪽 (Oenjjok) - Left. [wɛn.tɕok]",
      "2. 오른쪽 (Oreunjjok) - Right. [o.ɾɯn.tɕok]",
      "3. 바다 (Bada) - Sea. [pa.da]",
      "4. 거리 (Geori) - Street. [kʌ.ɾi]",
      "Directions:",
      "반복해주세요 (Banbokhaejuseyo) - Repeat that, please. [pan.bo.kʰe.dʑu.se.jo]",
      "걸으세요 (Georeuseyo) - Walk. [kʌ.ɾɯ.se.jo]",
      "Additional words:",
      "지름길 (Jireumgil) - Shortcut. [tɕi.ɾɯm.kil]",
      "비행기 (Bihaenggi) - Airplane. [pi.hɛŋ.gi]"
    ],
    korean: [
      "",
      "왼쪽",
      "오른쪽",
      "바다",
      "거리",
      "",
      "반복해주세요",
      "걸으세요",
      "",
      "지름길",
      "비행기"
    ]
  },
    "Lesson 8: Family and Relationships": {
    text: [
      "1. Basic Family Terms:",
      "Family Members:",
      "아버지 (Abeoji) = Father",
      "어머니 (Eomeoni) = Mother",
      "형 (Hyeong) = Older brother (for males)",
      "오빠 (Oppa) = Older brother (for females)",
      "누나 (Nuna) = Older sister (for males)",
      "언니 (Unni) = Older sister (for females)",
      "동생 (Dongsaeng) = Younger sibling (for both genders)",
      "할아버지 (Halabeoji) = Grandfather",
      "할머니 (Halmeoni) = Grandmother",
      "아들 (Adeul) = Son",
      "딸 (Ttal) = Daughter",
      "2. Extended Family Terms:",
      "삼촌 (Samchon) = Uncle (father’s side)",
      "고모 (Gomo) = Aunt (father’s side)",
      "이모 (Imo) = Aunt (mother’s side)",
      "외삼촌 (Woesamchon) = Uncle (mother’s side)",
      "조카 (Joka) = Nephew/Niece",
      "사촌 (Sachon) = Cousin",
      "3. Explaining Family Relationships:",
      "저는 아버지와 어머니가 계세요. (I have a father and a mother.)\nJeo-neun a-beo-ji-wa eo-meo-ni-ga gye-se-yo.",
      "형은 나보다 세 살 많아요. (My older brother is three years older than me.)\nHyeong-eun na-bo-da se sal man-a-yo.",
      "할아버지는 집 근처에 사세요. (My grandfather lives near my house.)\nHal-a-beo-ji-neun jib geun-cheo-e sa-se-yo.",
      "사촌과 함께 놀아요. (I play with my cousin.)\nSa-cho-n-gwa ham-kke no-ra-yo.",
      "4. Questions and Answers Related to Family:",
      "Q: 당신의 가족은 몇 명이에요? (How many people are in your family?)\nA: 저희 가족은 네 명이에요. (My family has four people.)\nJeo-hui ga-jok-eun ne myeong-i-e-yo.",
      "Q: 형제/자매가 있어요? (Do you have any siblings?)\nA: 네, 저는 동생이 있어요. (Yes, I have a younger sibling.)\nNe, jeo-neun dong-saeng-i it-seo-yo."
    ],
    korean: [
      "",
      "",
      "아버지",
      "어머니",
      "형",
      "오빠",
      "누나",
      "언니",
      "동생",
      "할아버지",
      "할머니",
      "아들",
      "딸",
      "",
      "삼촌",
      "고모",
      "이모",
      "외삼촌",
      "조카",
      "사촌",
      "",
      "저는 아버지와 어머니가 계세요.",
      "형은 나보다 세 살 많아요.",
      "할아버지는 집 근처에 사세요.",
      "사촌과 함께 놀아요.",
      "당신의 가족은 몇 명이에요?",
      "저희 가족은 네 명이에요.",
      "형제/자매가 있어요?",
      "네, 저는 동생이 있어요."
    ]
  },
    "Lesson 9: Colors and Adjectives": {
    text: [
      "List of Colors:",
      "빨간색 (Ppal-gan-saek) = Red",
      "파란색 (Pa-ran-saek) = Blue",
      "노란색 (No-ran-saek) = Yellow",
      "초록색 (Cho-rok-saek) = Green",
      "검정색 (Geom-jeong-saek) = Black",
      "흰색 (Huin-saek) = White",
      "주황색 (Ju-hwang-saek) = Orange",
      "분홍색 (Bun-hong-saek) = Pink",
      "보라색 (Bo-ra-saek) = Purple",
      "갈색 (Gal-saek) = Brown",
      "회색 (Hoe-saek) = Gray",
      "Learning Expressions to Describe Colors:",
      "이것은 빨간색이에요. (This is red.) I-geos-eun ppal-gan-saek-i-e-yo.",
      "그 차는 파란색이에요. (That car is blue.) Geu cha-neun pa-ran-saek-i-e-yo.",
      "저는 초록색을 좋아해요. (I like green.) Jeo-neun cho-rok-saek-eul jo-a-hae-yo.",
      "이 꽃은 노란색이에요. (This flower is yellow.) I kkot-eun no-ran-saek-i-e-yo.",
      "이 신발은 검정색이에요. (These shoes are black.) I sin-bal-eun geom-jeong-saek-i-e-yo.",
      "Questions and Answers Related to Colors: ",
      "Q: 가장 좋아하는 색깔은 무엇이에요? (What is your favorite color?)\nA: 저는 파란색을 좋아해요. (I like blue.)",
      "Q: 이건 무슨 색이에요? (What color is this?)\nA: 이건 빨간색이에요. (This is red.)",
      "Q: 이 옷은 무슨 색이에요? (What color is this shirt?)\nA: 이 옷은 흰색이에요. (This shirt is white.)"
    ],
    korean: [
      "",
      "빨간색",
      "파란색",
      "노란색",
      "초록색",
      "검정색",
      "흰색",
      "주황색",
      "분홍색",
      "보라색",
      "갈색",
      "회색",
      "",
      "이것은 빨간색이에요.",
      "그 차는 파란색이에요.",
      "저는 초록색을 좋아해요.",
      "이 꽃은 노란색이에요.",
      "이 신발은 검정색이에요.",
      "",
      "가장 좋아하는 색깔은 무엇이에요?\n저는 파란색을 좋아해요.",
      "이건 무슨 색이에요?\n이건 빨간색이에요.",
      "이 옷은 무슨 색이에요?\n이 옷은 흰색이에요."
    ]
  },
  "Lesson 10: Culture and Customs": {
    text: [
      "Cultural phrases:",
      "1. 공공장소에서 미소 지으세요 (Gonggongjangsoeseo miso jieuseyo) - Smile in public. [koŋ.goŋ.dʑaŋ.so.e.seo mi.so dʑi.ɯ.se.jo]",
      "2. 겸손하세요 (Gyeomsonhaseyo) - Be humble. [kjʌm.son.ha.se.jo]",
      "3. 정리해주세요 (Jeongrihaejuseyo) - Tidy up. [tɕʌŋ.ɾi.hɛ.dʑu.se.jo]",
      "4. 배움 (Baeum) - Learning. [pɛ.um]",
      "Extra phrases:",
      "외국 문화 (Oeguk munhwa) - Foreign culture. [we.guk mun.hwa]",
      "학문 운동 (Hakmun undong) - Academic movement. [hak.mun un.doŋ]"
    ],
    korean: [
      "",
      "공공장소에서 미소 지으세요",
      "겸손하세요",
      "정리해주세요",
      "배움",
      "",
      "외국 문화",
      "학문 운동"
    ]
  }
};
